GET https://pd-retailer.local/wp-json/pressody_conductor/v1/solutions
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pressody_conductor
Accept: application/json

###

GET https://pd-retailer.local/wp-json/pressody_conductor/v1/solutions/parts
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pressody_conductor
Accept: application/json

###

GET https://pd-retailer.local/wp-json/pressody_conductor/v1/solutions/processed
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pressody_conductor
Accept: application/json

###

GET https://pd-retailer.local/wp-json/pressody_conductor/v1/solutions/processed
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pressody_conductor
Accept: application/json
Content-Type: application/json

{
  "solutionsContext": {
	"pressody-conductor/first-solution": {
	  "timestamp": 101
	},
	"pressody-conductor/fourth-solution": {
	  "timestamp": 102
	},
	"pressody-conductor/second-solution": {
	  "timestamp": 103
	},
	"pressody-conductor/third-solution": {
	  "timestamp": 104
	}
  }
}

###

POST https://pd-retailer.local/wp-json/pressody_conductor/v1/compositions/details_to_update
Authorization: Basic whtg94kNGV20FuOy7yTbqAi198hBMjyz pressody_conductor
Accept: application/json
Content-Type: application/json

{
  "composer": {
	"name": "pressody\/my-site",
	"type": "project",
	"license": "MIT",
	"description": "A Pressody WordPress site.",
	"homepage": "https:\/\/local.local",
	"time": "2021-06-18T10:46:35+00:00",
	"authors": [
	  {
		"name": "Vlad Olaru",
		"email": "vlad@pixelgrade.com",
		"homepage": "https:\/\/thinkwritecode.com",
		"role": "Development, infrastructure, and product development"
	  }
	],
	"keywords": [],
	"support": {
	  "issues": "https:\/\/pressody.com",
	  "forum": "https:\/\/pressody.com"
	},
	"repositories": [
	  {
		"type": "composer",
		"url": "https:\/\/pd-records.local\/pdpackagist\/",
		"options": {
		  "ssl": {
			"verify_peer": false
		  }
		}
	  },
	  {
		"type": "composer",
		"url": "https:\/\/repo.packagist.org"
	  }
	],
	"require": {
	  "pressody-records\/part_another-test": "*, >=3.0.0",
	  "pressody-records\/part_test-test": "*, ^4.0",
	  "pressody-records\/part_yet-another": "*"
	},
	"require-dev": {},
	"config": {
	  "optimize-autoloader": true,
	  "preferred-install": "dist"
	},
	"minimum-stability": "stable",
	"prefer-stable": false,
	"extra": {
	  "installer-paths": {
		"web\/app\/mu-plugins\/{$name}\/": [
		  "type:wordpress-muplugin"
		],
		"web\/app\/plugins\/{$name}\/": [
		  "type:wordpress-plugin"
		],
		"web\/app\/themes\/{$name}\/": [
		  "type:wordpress-theme"
		]
	  },
	  "pd-required-packages": {
		"pressody-records\/part_yet-another": {
		  "name": "pressody-records\/part_yet-another",
		  "version": "*",
		  "requiredBy": [
			{
			  "name": "pressody-conductor\/first-solution",
			  "requiredVersion": "*"
			}
		  ]
		},
		"pressody-records\/part_another-test": {
		  "name": "pressody-records\/part_another-test",
		  "version": "*, >=3.0.0",
		  "requiredBy": [
			{
			  "name": "pressody-conductor\/fourth-solution",
			  "requiredVersion": "*"
			},
			{
			  "name": "pressody-conductor\/second-solution",
			  "requiredVersion": ">=3.0.0"
			}
		  ]
		},
		"pressody-records\/part_test-test": {
		  "name": "pressody-records\/part_test-test",
		  "version": "*, ^4.0",
		  "requiredBy": [
			{
			  "name": "pressody-conductor\/fourth-solution",
			  "requiredVersion": "*"
			},
			{
			  "name": "pressody-conductor\/second-solution",
			  "requiredVersion": "^4.0"
			}
		  ]
		}
	  },
	  "pd-user": "def5020022eeae1880bd161ba2cf48f1afc4fec03ba2396bcb0124678fe9195f2260c6431e51b0e6d1adea9f0e17b1865702b5e1d980c8c467310b44ef643bbf02b2729eba6197244adb2146ab2814b47e168a2441af7dce5253abc0e13cf4e74ca9ec731f97cbce864e3a3458cf44d832600090d3eda972b337a89188ca28551d59b0a63f",
	  "wordpress-install-dir": "web\/wp",
	  "pd-fingerprint": "44e4291a4eb8be042e08da3fb6f96ce4"
	},
	"scripts": {
	  "post-root-package-install": [
		"php -r \"copy('.env.example', '.env');\""
	  ],
	  "test": [
		"phpcs"
	  ]
	}
  }
}

###

POST https://pd-retailer.local/wp-json/pressody_conductor/v1/compositions/check_user_details
Authorization: Basic whtg94kNGV20FuOy7yTbqAi198hBMjyz pressody_conductor
Accept: application/json
Content-Type: application/json

{
  "user": "def502005762a1f7ab01944a6224811e40d61b97df9d0e155281b57a686c1cd9bf3dd1d7e636c69067bae573142d6b9560df6389000ba5e122bdee49947bfe09329ccb6b424c12d1e71416314661763df5d69ec3b5c7c84fad512b94c1fed6ee7df3b07a8b0b0aab80ac2ff855859286a417ffb9d927b7ce8d67b7989fc48c849b79e261f4e235201478d5613a8be7976bc301e45bdf17227d27f0133480"
}

###

POST https://pd-retailer.local/wp-json/pressody_conductor/v1/compositions/encrypt_user_details
Authorization: Basic whtg94kNGV20FuOy7yTbqAi198hBMjyz pressody_conductor
Accept: application/json
Content-Type: application/json

{
  "userid": 1,
  "compositionid": "sdfsdwaqt",
  "extra": {
	"email": "test@test.com"
  }
}

###
